########################################
## CONFIG | Configuration Store Configs
## See aiSSEMBLE aissemble-configuration-store-chart: README for more details.
## https://github.com/boozallen/aissemble/
########################################

aissemble-configuration-store-chart:
  aissemble-quarkus-chart:
    deployment:
      image:
        imagePullPolicy: IfNotPresent


